export interface EmojiEntry {
  char: string;
  keywords: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  emojis: EmojiEntry[];
}

/** Bibliothèque d'emoji façon clavier iOS/Android, groupée par catégorie avec mots-clés en
 * français pour la recherche — tout est statique/embarqué, aucun appel réseau. */
export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "voyages",
    label: "Voyages",
    emojis: [
      { char: "✈️", keywords: "avion vol aéroport voyage" },
      { char: "🧳", keywords: "valise bagage voyage" },
      { char: "🗺️", keywords: "carte plan itinéraire" },
      { char: "🧭", keywords: "boussole direction navigation" },
      { char: "🏝️", keywords: "île plage tropical vacances" },
      { char: "🏖️", keywords: "plage parasol vacances" },
      { char: "🏔️", keywords: "montagne neige sommet" },
      { char: "⛺", keywords: "tente camping" },
      { char: "🚗", keywords: "voiture route transport" },
      { char: "🚌", keywords: "bus transport" },
      { char: "🚆", keywords: "train rail transport" },
      { char: "🚢", keywords: "bateau navire croisière" },
      { char: "🛳️", keywords: "paquebot croisière bateau" },
      { char: "🚀", keywords: "fusée espace départ" },
      { char: "🛂", keywords: "passeport douane contrôle" },
      { char: "🎫", keywords: "billet ticket" },
      { char: "🧿", keywords: "porte-bonheur amulette" },
      { char: "🌍", keywords: "monde terre globe europe afrique" },
      { char: "🌎", keywords: "monde terre globe amérique" },
      { char: "🌏", keywords: "monde terre globe asie" },
      { char: "🚏", keywords: "arrêt bus transport" },
      { char: "🛶", keywords: "canoë kayak bateau" },
      { char: "🏕️", keywords: "camping tente nature" },
      { char: "🗽", keywords: "statue liberté monument" },
      { char: "🕌", keywords: "mosquée monument" },
      { char: "🛵", keywords: "scooter moto transport" },
      { char: "🚲", keywords: "vélo bicyclette transport" },
      { char: "🚕", keywords: "taxi transport" },
      { char: "🚁", keywords: "hélicoptère survol" },
      { char: "🛫", keywords: "décollage avion départ" },
      { char: "🛬", keywords: "atterrissage avion arrivée" },
      { char: "⛴️", keywords: "ferry traversier bateau" },
      { char: "🚡", keywords: "téléphérique montagne" },
      { char: "🎡", keywords: "grande roue attraction" },
      { char: "🎢", keywords: "montagnes russes attraction" },
      { char: "🗼", keywords: "tour monument" },
      { char: "🏰", keywords: "château monument" },
      { char: "⛩️", keywords: "sanctuaire japon monument" },
      { char: "🕍", keywords: "synagogue monument" },
      { char: "⛪", keywords: "église monument" },
      { char: "🏛️", keywords: "musée monument colonnes" },
      { char: "🎪", keywords: "chapiteau cirque festival" },
      { char: "🛍️", keywords: "shopping achats sacs" },
      { char: "🌅", keywords: "lever de soleil aube" },
      { char: "🌄", keywords: "lever de soleil montagne" },
      { char: "🌇", keywords: "coucher de soleil ville" },
      { char: "🏨", keywords: "hôtel logement" },
      { char: "🛎️", keywords: "réception hôtel service" },
      { char: "🔑", keywords: "clé chambre hôtel" },
      { char: "🚦", keywords: "feu circulation route" },
      { char: "🛣️", keywords: "route autoroute" },
    ],
  },
  {
    id: "activites",
    label: "Activités",
    emojis: [
      { char: "⚽", keywords: "football sport ballon" },
      { char: "🏀", keywords: "basket sport ballon" },
      { char: "🎾", keywords: "tennis sport" },
      { char: "🏄", keywords: "surf sport plage" },
      { char: "🚴", keywords: "vélo cyclisme sport" },
      { char: "🏃", keywords: "course running sport" },
      { char: "🧗", keywords: "escalade grimpe sport" },
      { char: "🏊", keywords: "natation piscine sport" },
      { char: "⛷️", keywords: "ski hiver sport" },
      { char: "🎣", keywords: "pêche loisir" },
      { char: "🎨", keywords: "art peinture créativité" },
      { char: "🎭", keywords: "théâtre spectacle" },
      { char: "🎬", keywords: "cinéma film" },
      { char: "🎮", keywords: "jeu vidéo manette" },
      { char: "🎸", keywords: "guitare musique" },
      { char: "🎧", keywords: "musique casque écoute" },
      { char: "📷", keywords: "photo appareil photographie" },
      { char: "📚", keywords: "livre lecture bibliothèque" },
      { char: "🧩", keywords: "puzzle jeu casse-tête" },
      { char: "🎲", keywords: "dé jeu société" },
      { char: "🧘", keywords: "yoga méditation détente" },
      { char: "🏆", keywords: "trophée victoire récompense" },
      { char: "🎯", keywords: "cible objectif précision" },
      { char: "🪁", keywords: "cerf-volant loisir" },
      { char: "🏋️", keywords: "musculation sport gym" },
      { char: "🤸", keywords: "gymnastique sport" },
      { char: "🏇", keywords: "équitation cheval sport" },
      { char: "🧑‍🎤", keywords: "chant concert musique" },
      { char: "🎻", keywords: "violon musique" },
      { char: "🥁", keywords: "batterie musique" },
      { char: "🎹", keywords: "piano musique" },
      { char: "🎤", keywords: "micro chant karaoké" },
      { char: "🕹️", keywords: "manette jeu rétro" },
      { char: "♟️", keywords: "échecs jeu stratégie" },
      { char: "🃏", keywords: "cartes jeu" },
      { char: "🧵", keywords: "couture fil loisir créatif" },
      { char: "🪡", keywords: "couture aiguille" },
      { char: "🪴", keywords: "jardinage plante" },
      { char: "🍿", keywords: "popcorn cinéma soirée" },
      { char: "🎳", keywords: "bowling loisir" },
      { char: "🛼", keywords: "roller patin loisir" },
      { char: "🏂", keywords: "snowboard hiver sport" },
      { char: "🤿", keywords: "plongée sport mer" },
      { char: "🪂", keywords: "parachute sport extrême" },
      { char: "🎿", keywords: "ski sport hiver" },
    ],
  },
  {
    id: "nature",
    label: "Nature",
    emojis: [
      { char: "☀️", keywords: "soleil beau temps" },
      { char: "🌤️", keywords: "nuage soleil temps" },
      { char: "🌧️", keywords: "pluie temps" },
      { char: "⛅", keywords: "nuage temps" },
      { char: "❄️", keywords: "neige flocon hiver" },
      { char: "🌈", keywords: "arc-en-ciel" },
      { char: "🌊", keywords: "vague mer océan" },
      { char: "🌳", keywords: "arbre nature forêt" },
      { char: "🌲", keywords: "sapin arbre nature" },
      { char: "🌵", keywords: "cactus désert" },
      { char: "🌸", keywords: "fleur cerisier printemps" },
      { char: "🌻", keywords: "tournesol fleur" },
      { char: "🍁", keywords: "feuille automne" },
      { char: "🦋", keywords: "papillon insecte" },
      { char: "🐬", keywords: "dauphin animal mer" },
      { char: "🐘", keywords: "éléphant animal safari" },
      { char: "🦁", keywords: "lion animal safari" },
      { char: "🐢", keywords: "tortue animal" },
      { char: "🌋", keywords: "volcan montagne" },
      { char: "🪐", keywords: "planète espace" },
      { char: "⭐", keywords: "étoile" },
      { char: "🌙", keywords: "lune nuit" },
      { char: "⛈️", keywords: "orage tonnerre temps" },
      { char: "🌩️", keywords: "éclair orage temps" },
      { char: "🌪️", keywords: "tornade temps" },
      { char: "🌫️", keywords: "brouillard brume temps" },
      { char: "💨", keywords: "vent rafale" },
      { char: "🔥", keywords: "feu chaleur" },
      { char: "🌿", keywords: "plante herbe nature" },
      { char: "🍀", keywords: "trèfle chance nature" },
      { char: "🌱", keywords: "pousse plante jeune" },
      { char: "🌷", keywords: "tulipe fleur" },
      { char: "🌹", keywords: "rose fleur" },
      { char: "🌺", keywords: "fleur hibiscus tropical" },
      { char: "🍂", keywords: "feuilles mortes automne" },
      { char: "🍃", keywords: "feuilles vent nature" },
      { char: "🦉", keywords: "hibou chouette animal" },
      { char: "🦊", keywords: "renard animal" },
      { char: "🐺", keywords: "loup animal" },
      { char: "🦌", keywords: "cerf animal forêt" },
      { char: "🐻", keywords: "ours animal" },
      { char: "🐧", keywords: "manchot pingouin animal" },
      { char: "🦅", keywords: "aigle oiseau" },
      { char: "🐝", keywords: "abeille insecte" },
      { char: "🐌", keywords: "escargot lent" },
      { char: "🐙", keywords: "poulpe mer animal" },
      { char: "🐠", keywords: "poisson tropical mer" },
      { char: "🦈", keywords: "requin mer animal" },
      { char: "🐳", keywords: "baleine mer animal" },
    ],
  },
  {
    id: "nourriture",
    label: "Nourriture",
    emojis: [
      { char: "🍕", keywords: "pizza repas" },
      { char: "🍔", keywords: "burger repas" },
      { char: "🍜", keywords: "nouilles soupe repas" },
      { char: "🍣", keywords: "sushi japon repas" },
      { char: "🥗", keywords: "salade repas sain" },
      { char: "🍰", keywords: "gâteau dessert" },
      { char: "☕", keywords: "café boisson" },
      { char: "🍷", keywords: "vin boisson" },
      { char: "🍹", keywords: "cocktail boisson vacances" },
      { char: "🍺", keywords: "bière boisson" },
      { char: "🥐", keywords: "croissant petit-déjeuner" },
      { char: "🍎", keywords: "pomme fruit" },
      { char: "🍇", keywords: "raisin fruit" },
      { char: "🥑", keywords: "avocat fruit sain" },
      { char: "🍫", keywords: "chocolat" },
      { char: "🍦", keywords: "glace dessert" },
      { char: "🍌", keywords: "banane fruit" },
      { char: "🍊", keywords: "orange clémentine fruit" },
      { char: "🍋", keywords: "citron fruit" },
      { char: "🍓", keywords: "fraise fruit" },
      { char: "🍑", keywords: "pêche abricot fruit" },
      { char: "🍐", keywords: "poire fruit" },
      { char: "🍍", keywords: "ananas fruit" },
      { char: "🍉", keywords: "pastèque fruit" },
      { char: "🍈", keywords: "melon fruit" },
      { char: "🥭", keywords: "mangue fruit" },
      { char: "🥝", keywords: "kiwi fruit" },
      { char: "🍒", keywords: "cerise fruit" },
      { char: "🥕", keywords: "carotte légume" },
      { char: "🥔", keywords: "pomme de terre patate légume" },
      { char: "🍅", keywords: "tomate légume" },
      { char: "🥬", keywords: "salade laitue légume" },
      { char: "🥦", keywords: "brocoli légume" },
      { char: "🫑", keywords: "poivron légume" },
      { char: "🥒", keywords: "concombre légume" },
      { char: "🍄", keywords: "champignon" },
      { char: "🧅", keywords: "oignon" },
      { char: "🧄", keywords: "ail" },
      { char: "🌽", keywords: "maïs légume" },
      { char: "🍆", keywords: "aubergine légume" },
      { char: "🌶️", keywords: "piment épice" },
      { char: "🥜", keywords: "cacahuète noix apéritif" },
      { char: "🍗", keywords: "poulet volaille viande" },
      { char: "🥩", keywords: "steak viande boeuf" },
      { char: "🥓", keywords: "bacon lardon charcuterie" },
      { char: "🌭", keywords: "hot-dog saucisse" },
      { char: "🍖", keywords: "viande os gigot" },
      { char: "🐟", keywords: "poisson" },
      { char: "🍤", keywords: "crevette fruits de mer" },
      { char: "🦪", keywords: "huître fruits de mer" },
      { char: "🥚", keywords: "œuf" },
      { char: "🥛", keywords: "lait" },
      { char: "🧀", keywords: "fromage mozzarella camembert" },
      { char: "🥣", keywords: "yaourt céréales bol" },
      { char: "🧈", keywords: "beurre" },
      { char: "🥖", keywords: "pain baguette" },
      { char: "🍞", keywords: "pain tranché toast" },
      { char: "🥯", keywords: "bagel viennoiserie" },
      { char: "🥞", keywords: "crêpe pancake petit-déjeuner" },
      { char: "🧇", keywords: "gaufre petit-déjeuner" },
      { char: "🍩", keywords: "donut beignet dessert" },
      { char: "🍪", keywords: "biscuit cookie" },
      { char: "🥧", keywords: "tarte dessert" },
      { char: "🍚", keywords: "riz" },
      { char: "🍝", keywords: "pâtes spaghetti" },
      { char: "🥫", keywords: "conserve soupe boîte" },
      { char: "🧂", keywords: "sel poivre épice" },
      { char: "🫒", keywords: "huile olive" },
      { char: "🍯", keywords: "miel confiture sucre" },
      { char: "🌾", keywords: "farine céréale blé" },
      { char: "🥥", keywords: "noix de coco" },
      { char: "🌰", keywords: "châtaigne noix" },
      { char: "🍿", keywords: "popcorn snack" },
      { char: "🍭", keywords: "sucette bonbon" },
      { char: "🍬", keywords: "bonbon confiserie" },
      { char: "🧊", keywords: "glaçon surgelé froid" },
      { char: "💧", keywords: "eau boisson" },
      { char: "🧃", keywords: "jus brique boisson" },
      { char: "🥤", keywords: "soda gobelet boisson" },
      { char: "🍵", keywords: "thé infusion boisson" },
      { char: "🍾", keywords: "champagne fête bouteille" },
      { char: "🥃", keywords: "whisky rhum alcool" },
      { char: "🍸", keywords: "cocktail apéritif verre" },
      { char: "🥘", keywords: "plat mijoté cuisine" },
      { char: "🍲", keywords: "ragoût pot-au-feu" },
      { char: "🥙", keywords: "kebab sandwich pain garni" },
      { char: "🌮", keywords: "taco mexicain" },
      { char: "🌯", keywords: "burrito wrap" },
      { char: "🍛", keywords: "curry riz" },
      { char: "🍱", keywords: "bento repas japonais" },
      { char: "🍥", keywords: "surimi poisson japonais" },
      { char: "🥟", keywords: "raviole dumpling" },
      { char: "🧆", keywords: "falafel" },
      { char: "🫓", keywords: "pain plat pita naan" },
    ],
  },
  {
    id: "bureau",
    label: "Objets & bureau",
    emojis: [
      { char: "💼", keywords: "mallette travail bureau" },
      { char: "📁", keywords: "dossier fichier document" },
      { char: "📅", keywords: "calendrier date planning" },
      { char: "📌", keywords: "épingle punaise" },
      { char: "✏️", keywords: "crayon écriture note" },
      { char: "📝", keywords: "note mémo écriture" },
      { char: "📊", keywords: "graphique statistique" },
      { char: "📈", keywords: "graphique croissance progression" },
      { char: "🔧", keywords: "outil réparation bricolage" },
      { char: "🔨", keywords: "marteau outil bricolage" },
      { char: "🏠", keywords: "maison logement" },
      { char: "🏡", keywords: "maison jardin logement" },
      { char: "🏢", keywords: "immeuble bureau entreprise" },
      { char: "🛠️", keywords: "outils bricolage rénovation" },
      { char: "📦", keywords: "carton colis déménagement" },
      { char: "🔑", keywords: "clé accès sécurité" },
      { char: "💡", keywords: "idée ampoule inspiration" },
      { char: "🖥️", keywords: "ordinateur informatique" },
      { char: "📱", keywords: "téléphone mobile" },
      { char: "🧰", keywords: "boîte à outils bricolage" },
      { char: "🖨️", keywords: "imprimante bureau" },
      { char: "🗄️", keywords: "classeur archive bureau" },
      { char: "🖇️", keywords: "trombone bureau" },
      { char: "📎", keywords: "trombone attache" },
      { char: "✂️", keywords: "ciseaux couper" },
      { char: "📐", keywords: "règle géométrie" },
      { char: "🗑️", keywords: "poubelle corbeille" },
      { char: "🧽", keywords: "éponge ménage nettoyage" },
      { char: "🧹", keywords: "balai ménage" },
      { char: "🪣", keywords: "seau ménage" },
      { char: "🧺", keywords: "panier linge lessive" },
      { char: "🛋️", keywords: "canapé salon mobilier" },
      { char: "🛏️", keywords: "lit chambre mobilier" },
      { char: "🚿", keywords: "douche salle de bain" },
      { char: "🛁", keywords: "baignoire salle de bain" },
      { char: "🪟", keywords: "fenêtre maison" },
      { char: "🚪", keywords: "porte entrée maison" },
      { char: "💡", keywords: "ampoule lumière" },
      { char: "🔌", keywords: "prise électrique branchement" },
      { char: "🪜", keywords: "échelle bricolage" },
      { char: "🧱", keywords: "brique construction" },
      { char: "🪚", keywords: "scie bricolage outil" },
      { char: "🪛", keywords: "tournevis bricolage outil" },
    ],
  },
  {
    id: "argent",
    label: "Argent & travail",
    emojis: [
      { char: "💰", keywords: "argent économie sac" },
      { char: "💶", keywords: "euro argent monnaie" },
      { char: "💳", keywords: "carte bancaire paiement" },
      { char: "🏦", keywords: "banque finance" },
      { char: "📉", keywords: "graphique baisse finance" },
      { char: "🧾", keywords: "facture reçu dépense" },
      { char: "🎯", keywords: "objectif cible" },
      { char: "🚀", keywords: "lancement croissance projet" },
      { char: "🏗️", keywords: "chantier construction rénovation" },
      { char: "⚖️", keywords: "balance juridique équilibre" },
      { char: "🎓", keywords: "diplôme études formation" },
      { char: "💍", keywords: "bague mariage fiançailles" },
      { char: "👶", keywords: "bébé naissance famille" },
      { char: "🐾", keywords: "animal patte compagnie" },
      { char: "🪙", keywords: "pièce monnaie" },
      { char: "💵", keywords: "billet dollar argent" },
      { char: "💷", keywords: "livre sterling argent" },
      { char: "📄", keywords: "document contrat" },
      { char: "🖋️", keywords: "signature stylo contrat" },
      { char: "🤝", keywords: "poignée de main accord" },
      { char: "🏬", keywords: "commerce magasin" },
      { char: "🛒", keywords: "courses caddie achats" },
      { char: "🧑‍💼", keywords: "employé bureau travail" },
    ],
  },
  {
    id: "symboles",
    label: "Symboles",
    emojis: [
      { char: "❤️", keywords: "cœur amour" },
      { char: "⭐", keywords: "étoile favori" },
      { char: "✨", keywords: "étincelles magie" },
      { char: "🔥", keywords: "feu tendance" },
      { char: "✅", keywords: "coché validé terminé" },
      { char: "⚡", keywords: "éclair énergie rapide" },
      { char: "🎉", keywords: "fête confettis célébration" },
      { char: "🎁", keywords: "cadeau surprise" },
      { char: "🏁", keywords: "drapeau damier arrivée" },
      { char: "🔔", keywords: "cloche notification alerte" },
      { char: "🧭", keywords: "boussole direction" },
      { char: "🌟", keywords: "étoile brillante réussite" },
      { char: "💎", keywords: "diamant précieux" },
      { char: "🔒", keywords: "cadenas sécurité" },
      { char: "🆕", keywords: "nouveau" },
      { char: "🗂️", keywords: "classeur organisation" },
      { char: "❗", keywords: "important attention" },
      { char: "❓", keywords: "question interrogation" },
      { char: "♻️", keywords: "recyclage écologie" },
      { char: "🌱", keywords: "écologie durable" },
      { char: "🏷️", keywords: "étiquette prix" },
      { char: "📍", keywords: "épingle localisation" },
      { char: "🔴", keywords: "rouge point important" },
      { char: "🟢", keywords: "vert point validé" },
      { char: "🟡", keywords: "jaune point attention" },
      { char: "🔵", keywords: "bleu point" },
      { char: "⏳", keywords: "sablier attente temps" },
      { char: "⏰", keywords: "réveil alarme heure" },
      { char: "🔁", keywords: "répétition récurrent boucle" },
    ],
  },
  {
    id: "personnes",
    label: "Personnes",
    emojis: [
      { char: "🙂", keywords: "sourire content" },
      { char: "😄", keywords: "sourire heureux" },
      { char: "🥳", keywords: "fête célébration content" },
      { char: "🧑", keywords: "personne" },
      { char: "👩", keywords: "femme personne" },
      { char: "👨", keywords: "homme personne" },
      { char: "🧑‍🤝‍🧑", keywords: "amis groupe personnes" },
      { char: "👨‍👩‍👧‍👦", keywords: "famille" },
      { char: "🧑‍💻", keywords: "informaticien travail ordinateur" },
      { char: "🧑‍🍳", keywords: "cuisinier chef cuisine" },
      { char: "🧑‍🎨", keywords: "artiste créativité" },
      { char: "🧑‍⚕️", keywords: "médecin santé" },
      { char: "🧑‍🏫", keywords: "enseignant professeur" },
      { char: "🧑‍✈️", keywords: "pilote avion" },
      { char: "👵", keywords: "grand-mère mamie personne âgée" },
      { char: "👴", keywords: "grand-père papy personne âgée" },
      { char: "🧒", keywords: "enfant" },
      { char: "👶", keywords: "bébé" },
      { char: "🧑‍🦱", keywords: "personne cheveux bouclés" },
      { char: "👩‍🦰", keywords: "femme rousse" },
      { char: "🧔", keywords: "barbe personne" },
      { char: "🧑‍🌾", keywords: "agriculteur jardinier" },
      { char: "🧑‍🔧", keywords: "mécanicien réparateur" },
      { char: "🧑‍🚀", keywords: "astronaute espace" },
      { char: "🧑‍🎓", keywords: "étudiant diplômé" },
      { char: "🧑‍⚖️", keywords: "juge justice" },
      { char: "🧑‍🚒", keywords: "pompier" },
      { char: "👮", keywords: "policier sécurité" },
      { char: "🕵️", keywords: "détective enquête" },
      { char: "🧙", keywords: "magicien fantaisie" },
      { char: "🦸", keywords: "super-héros" },
    ],
  },
];

/** Cherche un emoji par mot-clé (ou par le caractère lui-même) dans toutes les catégories. */
export function searchEmojis(query: string): EmojiEntry[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const seen = new Set<string>();
  const results: EmojiEntry[] = [];
  for (const category of EMOJI_CATEGORIES) {
    for (const entry of category.emojis) {
      if (seen.has(entry.char)) continue;
      if (entry.keywords.includes(q) || entry.char === q) {
        seen.add(entry.char);
        results.push(entry);
      }
    }
  }
  return results;
}
