export type CurrencyRef = { code: string; symbol: string; name: string };

/** Devises courantes (données embarquées, aucun appel réseau), EUR en tête car devise par défaut. */
export const CURRENCIES: CurrencyRef[] = [
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "USD", symbol: "$", name: "Dollar américain" },
  { code: "GBP", symbol: "£", name: "Livre sterling" },
  { code: "CHF", symbol: "CHF", name: "Franc suisse" },
  { code: "JPY", symbol: "¥", name: "Yen japonais" },
  { code: "CNY", symbol: "¥", name: "Yuan chinois" },
  { code: "CAD", symbol: "$", name: "Dollar canadien" },
  { code: "AUD", symbol: "$", name: "Dollar australien" },
  { code: "NZD", symbol: "$", name: "Dollar néo-zélandais" },
  { code: "MXN", symbol: "$", name: "Peso mexicain" },
  { code: "BRL", symbol: "R$", name: "Real brésilien" },
  { code: "ARS", symbol: "$", name: "Peso argentin" },
  { code: "CLP", symbol: "$", name: "Peso chilien" },
  { code: "COP", symbol: "$", name: "Peso colombien" },
  { code: "PEN", symbol: "S/", name: "Sol péruvien" },
  { code: "THB", symbol: "฿", name: "Baht thaïlandais" },
  { code: "VND", symbol: "₫", name: "Dong vietnamien" },
  { code: "IDR", symbol: "Rp", name: "Roupie indonésienne" },
  { code: "MYR", symbol: "RM", name: "Ringgit malaisien" },
  { code: "SGD", symbol: "$", name: "Dollar de Singapour" },
  { code: "PHP", symbol: "₱", name: "Peso philippin" },
  { code: "KRW", symbol: "₩", name: "Won sud-coréen" },
  { code: "INR", symbol: "₹", name: "Roupie indienne" },
  { code: "LKR", symbol: "Rs", name: "Roupie srilankaise" },
  { code: "NPR", symbol: "Rs", name: "Roupie népalaise" },
  { code: "AED", symbol: "د.إ", name: "Dirham des Émirats arabes unis" },
  { code: "SAR", symbol: "﷼", name: "Riyal saoudien" },
  { code: "TRY", symbol: "₺", name: "Livre turque" },
  { code: "EGP", symbol: "£E", name: "Livre égyptienne" },
  { code: "MAD", symbol: "د.م.", name: "Dirham marocain" },
  { code: "ZAR", symbol: "R", name: "Rand sud-africain" },
  { code: "KES", symbol: "KSh", name: "Shilling kényan" },
  { code: "PLN", symbol: "zł", name: "Zloty polonais" },
  { code: "CZK", symbol: "Kč", name: "Couronne tchèque" },
  { code: "HUF", symbol: "Ft", name: "Forint hongrois" },
  { code: "SEK", symbol: "kr", name: "Couronne suédoise" },
  { code: "NOK", symbol: "kr", name: "Couronne norvégienne" },
  { code: "DKK", symbol: "kr", name: "Couronne danoise" },
  { code: "ISK", symbol: "kr", name: "Couronne islandaise" },
  { code: "RUB", symbol: "₽", name: "Rouble russe" },
];
